/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsproject;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author williamng
 */
public class weekly extends javax.swing.JFrame {

    ArrayList<task> tasklist;
    String header[] = new String[]{"Task Name", "Note", "Priority", "Due Date"};
    DefaultTableModel dtm;
    int row, col;

    /**
     * Creates new form weekly
     */
    public weekly() {
        initComponents();
        tasklist = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        jTable1.setModel(dtm);
        this.setLocationRelativeTo(null);
    }

    private void populateTable() {
        dtm.setRowCount(0);
        //  task task1 = new task();
        for (int i = 0; i < tasklist.size(); i++) {
            Object[] objs = {tasklist.get(i).getTaskname(), tasklist.get(i).getTasknote(), tasklist.get(i).getPriority(), tasklist.get(i).getDate()};
            dtm.addRow(objs);
        }
    }

    private void clearField() {
        jtaskname.requestFocus();
        jtaskname.setText("");
        jnote.setText("");
        jpriority.setSelectedIndex(0);
        jdate.setDate(null);
    }

    private void resetArray() {
        tasklist.clear();
        clearField();
        dtm.setRowCount(0);
    }

    public void priorityButton(String taskPriority) {
        for (int j = 0; j < (jpriority.getItemCount()); j++) {
            if (jpriority.getItemAt(j).equalsIgnoreCase(taskPriority)) {
                jpriority.setSelectedIndex(j);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtaskname = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jpriority = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jnote = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WEEKLY TO-DO LIST");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204,200));
        jPanel2.setForeground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("WEEKLY TO-DO LIST");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 26, 414, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 90));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,200));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ADD A TASK : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        jLabel3.setText("DUE DATE : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, -1, -1));

        jLabel4.setText("NOTE : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 58, -1, -1));

        jLabel5.setText("PRIORITY : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 252, -1, -1));

        jtaskname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtasknameActionPerformed(evt);
            }
        });
        jPanel1.add(jtaskname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 17, 264, -1));
        jPanel1.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 174, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 84, -1));

        jpriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOW", "MEDIUM", "HIGH" }));
        jPanel1.add(jpriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 249, -1, -1));

        jnote.setColumns(20);
        jnote.setRows(5);
        jScrollPane2.setViewportView(jnote);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 58, 264, 173));

        jButton6.setText("RESET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 319, 84, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, 350));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204,30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Task Name", "Note", "Priority", "Due Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 537, 288));

        jButton4.setText("SEARCH TASK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jButton3.setText("UPDATE TASK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jButton2.setText("TASK DONE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 110, -1));

        jButton5.setText("RESET LIST");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 306, 109, 32));

        jButton7.setText("LOG OUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 344, 109, 32));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 550, 389));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsproject/todolist2.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 980, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtasknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtasknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtasknameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
            String taskname = jtaskname.getText();
            String tasknote = jnote.getText();
            String priority = jpriority.getSelectedItem().toString();
            String date = dformat.format(jdate.getDate());
            tasklist.add(new task(taskname, tasknote, priority, date)); // addtoarraylist
            populateTable();
            clearField();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "PLEASE INSERT ALL THE DETAILS !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            boolean ans = tasklist.isEmpty();
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "The the task is Complete ?", "DONE", dialogButton);
            if ((dialogResult == 0) && (ans == true)) {
                JOptionPane.showMessageDialog(this, "The TaskList is empty !!", "EMPTY LIST", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ((dialogResult == 0)) {
                dtm.removeRow(jTable1.getSelectedRow());
                tasklist.remove(row); //remove from arraylist
                populateTable();
                clearField();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please select a Task !!");
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //  try{
        boolean ans = tasklist.isEmpty();
        if (ans == true) {
            JOptionPane.showMessageDialog(this, "The LIST is empty !!", "EMPTY DATA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String input = JOptionPane.showInputDialog(this, "Search Task Name : ");

        for (int i = 0; i < tasklist.size(); i++) {
            if (tasklist.get(i).getTaskname().equalsIgnoreCase(input)) {
                JOptionPane.showMessageDialog(jButton4, "Task Found !", "Search Task", 1);
                jtaskname.setText(tasklist.get(i).getTaskname());
                jnote.setText(tasklist.get(i).getTasknote());
                String taskPriority = tasklist.get(i).getPriority();
                priorityButton(taskPriority);

                try {
                    Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String) dtm.getValueAt(row, 3).toString());
                    jdate.setDate(date);
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                return;
            }
        }
        return;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            boolean ans = tasklist.isEmpty();
            if (ans == true) {
                JOptionPane.showMessageDialog(this, "The LIST is empty !!", "EMPTY DATA", JOptionPane.ERROR_MESSAGE);
                return;
            }
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
            String updatetaskname = jtaskname.getText();
            String updatetasknote = jnote.getText();
            String updatepriority = jpriority.getSelectedItem().toString();
            String updatedate = dformat.format(jdate.getDate());

            tasklist.get(row).setTaskname(updatetaskname);// 
            tasklist.get(row).setTasknote(updatetasknote);//
            tasklist.get(row).setPriority(updatepriority);//
            tasklist.get(row).setDate(updatedate);
            populateTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please Select row to Update !!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        row = jTable1.getSelectedRow();
        col = jTable1.getColumnCount();
        System.out.println(row + "," + col);
        jtaskname.setText(dtm.getValueAt(row, 0).toString());
        jnote.setText(dtm.getValueAt(row, 1).toString());
        String taskPriority = dtm.getValueAt(row, 2).toString();
        priorityButton(taskPriority);
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String) dtm.getValueAt(row, 3).toString());
            jdate.setDate(date);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        boolean array = tasklist.isEmpty();
        int respone = JOptionPane.showConfirmDialog(this, "Are you sure want to RESET the LIST ?", "RESET LIST", JOptionPane.YES_NO_OPTION);
        if ((respone == JOptionPane.YES_OPTION) && (array == true)) {
            JOptionPane.showMessageDialog(this, "The list is Empty !", "Empty List Error", JOptionPane.ERROR_MESSAGE);
        } else if ((respone == JOptionPane.YES_OPTION)) {
            resetArray();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        taskLogin login = new taskLogin();

        int respone = JOptionPane.showConfirmDialog(this, "Are you sure want to logout ? ", "LOGOUT", JOptionPane.YES_NO_OPTION);

        if (respone == JOptionPane.YES_OPTION) {

            login.show();

            dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weekly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weekly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextArea jnote;
    private javax.swing.JComboBox<String> jpriority;
    private javax.swing.JTextField jtaskname;
    // End of variables declaration//GEN-END:variables
}
